### ISSUE TITLE
Failed to Load Mod Error with Forge 40.0.18 or 40.0.19

### ISSUE THREAD

**Issue by EldrinFal** [cc-tweaked/CC-Tweaked#1049]
### Minecraft Version

1.18.x

### Version

1.100.3

### Details

MC version 1.18.2
JAVA 18

[crash-2022-03-19_22.50.05-fml.txt](https://github.com/cc-tweaked/CC-Tweaked/files/8310688/crash-2022-03-19_22.50.05-fml.txt)

**Comment by SquidDev** [comment]
This was fixed in e6339b2847183927b70a690556c6835a1aa92c6b. I'll push a release soonish, just giving it a few more days to see if anything else crops up.

**Comment by WelpSTudent** [comment]
With latest patch, 1.100.4, it still crashes
https://gist.github.com/WelpSTudent/811679ea983dffac93d88bd68ab4af6e
